# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12, 2.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: maven
    - name: Change scala version to ${{matrix.scala}}
      run: bash ./build/change-scala-version.sh ${{matrix.scala}}
    - name: Build with Maven
      run: mvn -B install -DskipTests
    - name: Run coverage test
      run: mvn -B scoverage:report
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
    - uses: actions/upload-artifact@v3
      with:
        name: geomesa-sql-dist-package-${{matrix.scala}}
        path: geomesa-sql-dist/target/*.tar.gz

  smoke-accumulo:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Allow password-less ssh to localhost
      run: |
        if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
        fi
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - uses: actions/download-artifact@v3
      with:
        name: geomesa-sql-dist-package-2.12
        path: ./
    - name: Unpack the package
      run: mkdir -p geomesa-sql-dist && tar xf geomesa-sql-dist_2.12-*-bin.tar.gz --strip-components=1 -C geomesa-sql-dist
    - name: Checkout fluo-uno
      uses: actions/checkout@v3
      with:
        repository: bxkftechteam/fluo-uno
        ref: accumulo_2.1.0
        path: ./fluo-uno
    - run: ./fluo-uno/bin/uno fetch accumulo
    - run: ./fluo-uno/bin/uno setup accumulo
    - run: wget https://github.com/locationtech/geomesa/releases/download/geomesa-3.4.1/geomesa-accumulo_2.12-3.4.1-bin.tar.gz
    - run: tar xf geomesa-accumulo_2.12-3.4.1-bin.tar.gz
    - run: |
        export HADOOP_HOME=$(pwd)/fluo-uno/install/hadoop-3.3.4
        export ACCUMULO_HOME=$(pwd)/fluo-uno/install/accumulo-2.1.0
        export ZOOKEEPER_HOME=$(pwd)/fluo-uno/install/apache-zookeeper-3.8.0-bin
        export GEOMESA_HOME=$(pwd)/geomesa-accumulo_2.12-3.4.1
        export PATH=$HADOOP_HOME/bin:$ACCUMULO_HOME/bin:$GEOMESA_HOME/bin:$PATH
        yes | geomesa-accumulo
        setup-namespace.sh -u root -p secret -n geomesa
        geomesa-accumulo ingest -c geomesa.test -f beijing_subway build/smoke_test/beijing_subway.geojson --force
        geomesa-accumulo ingest -c geomesa.test -f beijing_subway_station build/smoke_test/beijing_subway_station.geojson --force
        ./geomesa-sql-dist/bin/geomesa-sqlline -c geomesa.test -f build/smoke_test/queries.sql

  smoke-hbase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12, 2.11]
        geomesa: [3.4.1]
    needs: build
    steps:
    - name: Allow password-less ssh to localhost
      run: |
        if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
        fi
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/download-artifact@v3
      with:
        name: geomesa-sql-dist-package-${{matrix.scala}}
        path: ./
    - name: Unpack the package
      run: mkdir -p geomesa-sql-dist && tar xf geomesa-sql-dist_${{matrix.scala}}-*-bin.tar.gz --strip-components=1 -C geomesa-sql-dist
    - name: Download hbase
      run: wget "https://dlcdn.apache.org/hbase/2.5.1/hbase-2.5.1-bin.tar.gz" && tar xf hbase-2.5.1-bin.tar.gz
    - run: wget https://github.com/locationtech/geomesa/releases/download/geomesa-${{matrix.geomesa}}/geomesa-hbase_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: tar xf geomesa-hbase_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - name: Setup HBase and GeoMesa coprocessor
      run: |
        cp -v geomesa-hbase_${{matrix.scala}}-${{matrix.geomesa}}/dist/hbase/geomesa-hbase-distributed-runtime-hbase2_${{matrix.scala}}-${{matrix.geomesa}}.jar hbase-2.5.1/lib/
        ./hbase-2.5.1/bin/start-hbase.sh
        while ! ./hbase-2.5.1/bin/hbase hbck ; do
          sleep 1
        done
    - run: |
        export HBASE_HOME=$(pwd)/hbase-2.5.1
        export GEOMESA_HOME=$(pwd)/geomesa-hbase_${{matrix.scala}}-${{matrix.geomesa}}
        export PATH=$HBASE_HOME/bin:$GEOMESA_HOME/bin:$PATH
        yes | geomesa-hbase
        geomesa-hbase ingest -c geomesa:test -f beijing_subway build/smoke_test/beijing_subway.geojson --force
        geomesa-hbase ingest -c geomesa:test -f beijing_subway_station build/smoke_test/beijing_subway_station.geojson --force
        ./geomesa-sql-dist/bin/geomesa-sqlline -c geomesa:test -f build/smoke_test/queries.sql

  smoke-redis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12, 2.11]
        geomesa: [3.4.1]
    needs: build
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/download-artifact@v3
      with:
        name: geomesa-sql-dist-package-${{matrix.scala}}
        path: ./
    - name: Unpack the package
      run: mkdir -p geomesa-sql-dist && tar xf geomesa-sql-dist_${{matrix.scala}}-*-bin.tar.gz --strip-components=1 -C geomesa-sql-dist
    - run: wget https://github.com/locationtech/geomesa/releases/download/geomesa-3.4.1/geomesa-redis_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: tar xf geomesa-redis_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: |
        export GEOMESA_HOME=$(pwd)/geomesa-redis_${{matrix.scala}}-${{matrix.geomesa}}
        export PATH=$GEOMESA_HOME/bin:$PATH
        yes | geomesa-redis
        geomesa-redis ingest -u localhost:6379 -c geomesa:test -f beijing_subway build/smoke_test/beijing_subway.geojson --force
        geomesa-redis ingest -u localhost:6379 -c geomesa:test -f beijing_subway_station build/smoke_test/beijing_subway_station.geojson --force
        ./geomesa-sql-dist/bin/geomesa-sqlline -c geomesa:test -p "redis.url=localhost:6379" -f build/smoke_test/queries.sql

  smoke-fs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12, 2.11]
        geomesa: [3.4.1]
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/download-artifact@v3
      with:
        name: geomesa-sql-dist-package-${{matrix.scala}}
        path: ./
    - name: Unpack the package
      run: mkdir -p geomesa-sql-dist && tar xf geomesa-sql-dist_${{matrix.scala}}-*-bin.tar.gz --strip-components=1 -C geomesa-sql-dist
    - run: wget https://github.com/locationtech/geomesa/releases/download/geomesa-3.4.1/geomesa-fs_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: tar xf geomesa-fs_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: |
        export GEOMESA_HOME=$(pwd)/geomesa-fs_${{matrix.scala}}-${{matrix.geomesa}}
        export PATH=$GEOMESA_HOME/bin:$PATH
        yes | geomesa-fs
        geomesa-fs ingest -p ./fs_store -e parquet --partition-scheme xz2-2bits -f beijing_subway build/smoke_test/beijing_subway.geojson --force
        geomesa-fs ingest -p ./fs_store -e parquet --partition-scheme xz2-2bits -f beijing_subway_station build/smoke_test/beijing_subway_station.geojson --force
        ./geomesa-sql-dist/bin/geomesa-sqlline -c ./fs_store -f build/smoke_test/queries.sql

  smoke-cassandra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.12, 2.11]
        geomesa: [3.4.1]
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/download-artifact@v3
      with:
        name: geomesa-sql-dist-package-${{matrix.scala}}
        path: ./
    - name: Unpack the package
      run: mkdir -p geomesa-sql-dist && tar xf geomesa-sql-dist_${{matrix.scala}}-*-bin.tar.gz --strip-components=1 -C geomesa-sql-dist
    - run: wget https://github.com/locationtech/geomesa/releases/download/geomesa-3.4.1/geomesa-cassandra_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - run: tar xf geomesa-cassandra_${{matrix.scala}}-${{matrix.geomesa}}-bin.tar.gz
    - name: Download cassandra
      run: wget "https://dlcdn.apache.org/cassandra/3.11.14/apache-cassandra-3.11.14-bin.tar.gz" && tar xf apache-cassandra-3.11.14-bin.tar.gz
    - name: Launch cassandra
      run: |
        ./apache-cassandra-3.11.14/bin/cassandra
        while ! ./apache-cassandra-3.11.14/bin/cqlsh -e 'describe cluster' ; do
          sleep 1
        done
    - run: |
        export CASSANDRA_HOME=$(pwd)/apache-cassandra-3.11.14
        export GEOMESA_HOME=$(pwd)/geomesa-cassandra_${{matrix.scala}}-${{matrix.geomesa}}
        export PATH=$CASSANDRA_HOME/bin:$GEOMESA_HOME/bin:$PATH
        yes | geomesa-cassandra
        cqlsh -e "CREATE KEYSPACE geomesa WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor' : 1};"
        geomesa-cassandra ingest -k geomesa -P localhost:9042 -c geomesa -f beijing_subway build/smoke_test/beijing_subway.geojson --force
        geomesa-cassandra ingest -k geomesa -P localhost:9042 -c geomesa -f beijing_subway_station build/smoke_test/beijing_subway_station.geojson --force
        ./geomesa-sql-dist/bin/geomesa-sqlline -c geomesa -p "cassandra.contact.point=localhost:9042;cassandra.keyspace=geomesa" -f build/smoke_test/queries.sql
